# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0829ad7bffba67e87baf2ec0475c4660d6583c7aabd7332b846476df4816edcb19d8091cfa43cd6e1a079b2bedc618763157ae886ed391ebcbe7fc2f9e12cbdd

test:
  secret_key_base: 8cad34766807ae54252256c26163d96a717012e3c4677c8152305b0ad778b76d1d9dda8ed1fc5125210ca21f68ec05e054f4fd2e8eb7ac1dc20048fec991cec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
